const DOMAIN_PREFIX = "https://api.mosoteach.cn/mssvc/index.php";
const CHECKIN_DOMAIN = "https://checkin.mosoteach.cn:19528/checkin";

const HMAC_SHA1_KEY_LOGIN = "836062733FDEAFEFAC684A134378F2C4"; //这个KEY应该只适用于固定的app_id、app_platform、app_version中，若修改app_id\app_platform\app_version，有潜在的可能导致key改变。原理：这个key其实是资源文件中的"logo_large_ios.jpg"的md5值

const HEADER_APP_ID = "MTIOS"; //理论上Header里的这些不重要，但是最好和后面的FORM保持一致
const HEADER_APP_VERSION = "5.3.1"; //理论上Header里的这些不重要，但是最好和后面的FORM保持一致
const HEADER_APP_MACHINE = "iPhone 12 Pro Max"; //随便填写
const HEADER_APP_SYSTEM_VERSION = "13.2"; //随便填写
const HEADER_DEVICE_CODE = "0C0698B9-3EDE-44D5-B786-326726356D1E"; //理论上Header里的这些不重要，但是最好和后面的FORM保持一致
const HEADER_DPR = "2.000000"; //估计是个缩放值，可以无视
const HEADER_USER_AGENT = "Teach/5.3.1 (iPhone; iOS " + HEADER_APP_SYSTEM_VERSION + "; Scale/" + HEADER_DPR + ")"; //UA

const FROM_LOGIN_PUBLIC_KEY = "MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDQdRyZtSoIDDmLoouJsy8nXlKk/0bnbH8GFfiHrALWmU+Cd7YllOvX9tB5uWNnrETsjLPH0cPQQSOCSxGVjBK7LeYBEPkCEyPB4cMU9SaEL6dR843Ag024p5eBzXVYiXLucWwaKXW4NY6sRdXpMu1EH4mXqqnPwD/8lKCRLik66wIDAQAB"; //这实际上是私钥密码(猜测)
const FORM_DEVICE_CODE = "0C0698B9-3EDE-44D5-B786-326726356D1E"; //随便的一个UUID，这个应该是友盟SDK用的东西，建议改成空白或者自己生成一个UUID
const FORM_DEVICE_PN_CODE = "asdhuw78374hsjeuf8s72y3nsjdu2nws874993847dehdnhewn2934nsjsj28324"; //64位的一个字符串，应该也是友盟SDK的东西，可以空白或者xjb写
const FORM_DEVICE_TYPE = "IOS"; //与上面HMAC_SHA1_KEY_LOGIN可能存在一定的关联，故不建议修改
const FORM_APP_ID = "MTIOS"; //与上面HMAC_SHA1_KEY_LOGIN可能存在一定的关联，故不建议修改
const FORM_APP_VERSION_NAME = "5.3.1"; //与上面HMAC_SHA1_KEY_LOGIN可能存在一定的关联，故不建议修改
const FORM_APP_VERSION_NUMBER = "130"; //与上面HMAC_SHA1_KEY_LOGIN可能存在一定的关联，故不建议修改
const FORM_SYSTEM_VERSION = "13.2"; //xjb写就行了，iOS系统版本


const PARAM_ENCYPT_RSA_PUBLIC_KEY = "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA1Kae4kdMkGYRGazq7y9gsVsK3NuwNVZGOWOKiabfoB8e4tRwaWko8+QN4fE9L9DbYT9TAtuS5EXyUm3dtUoieWIlLgR585G+aJYl+1naZymR25hx5KXyARzIxX/6b+E0QxDyridF0ON/jrxcVIS7wb8IURTRVePhDN2+h4n82S8S0zno3t5cVj+YRabS39n00mZMnYKvFDH757ZHRi8a1cdSAkUwQMFij1hCMrV9IuoK7Orjey5cOg5RsR2dKo2JIfnES6Mwl0gJPCqSc/Y3EZBqQHQyxsSyxGlwekTvhNYloL7Gv33Xuwdnrt1iOOu3KJ01992F7p9cewrQp0yvRwIDAQAB" //用于RSA加密登陆表单中的用户名和密码


global.DOMAIN_PREFIX = DOMAIN_PREFIX;
global.CHECKIN_DOMAIN = CHECKIN_DOMAIN;

global.HMAC_SHA1_KEY_LOGIN = HMAC_SHA1_KEY_LOGIN;

global.HEADER_APP_ID = HEADER_APP_ID;
global.HEADER_APP_VERSION = HEADER_APP_VERSION;
global.HEADER_APP_MACHINE = HEADER_APP_MACHINE;
global.HEADER_APP_SYSTEM_VERSION = HEADER_APP_SYSTEM_VERSION;
global.HEADER_DEVICE_CODE = HEADER_DEVICE_CODE;
global.HEADER_DPR = HEADER_DPR;
global.HEADER_USER_AGENT = HEADER_USER_AGENT;

global.FROM_LOGIN_PUBLIC_KEY = FROM_LOGIN_PUBLIC_KEY;
global.FORM_DEVICE_CODE = FORM_DEVICE_CODE;
global.FORM_DEVICE_PN_CODE = FORM_DEVICE_PN_CODE;
global.FORM_DEVICE_TYPE = FORM_DEVICE_TYPE;
global.FORM_APP_ID = FORM_APP_ID;
global.FORM_APP_VERSION_NAME = FORM_APP_VERSION_NAME;
global.FORM_APP_VERSION_NUMBER = FORM_APP_VERSION_NUMBER;
global.FORM_SYSTEM_VERSION = FORM_SYSTEM_VERSION;

global.PARAM_ENCYPT_RSA_PUBLIC_KEY = PARAM_ENCYPT_RSA_PUBLIC_KEY;